param(
  [Parameter(Mandatory = $true)]
  [string]$PhotoDir,
  [int]$MaxSize = 256,
  [int]$JpegQuality = 82
)

$ErrorActionPreference = 'Stop'
$base = Split-Path $PSScriptRoot -Parent
$outFile = Join-Path $base 'js\photos-data.js'

Add-Type -AssemblyName System.Drawing

function Get-CompressedDataUri {
  param([string]$Path, [int]$MaxSize, [int]$Quality)
  $img = [System.Drawing.Image]::FromFile($Path)
  try {
    $ratio = [Math]::Min($MaxSize / $img.Width, $MaxSize / $img.Height)
    if ($ratio -gt 1) { $ratio = 1 }
    $nw = [Math]::Max(1, [int]($img.Width * $ratio))
    $nh = [Math]::Max(1, [int]($img.Height * $ratio))
    $bmp = New-Object System.Drawing.Bitmap $nw, $nh
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.DrawImage($img, 0, 0, $nw, $nh)
    $g.Dispose()
    $encoder = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
    $encParams = New-Object System.Drawing.Imaging.EncoderParameters 1
    $encParams.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter ([System.Drawing.Imaging.Encoder]::Quality, [long]$Quality)
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, $encoder, $encParams)
    $bytes = $ms.ToArray()
    $bmp.Dispose()
    $ms.Dispose()
    return 'data:image/jpeg;base64,' + [Convert]::ToBase64String($bytes)
  }
  finally {
    $img.Dispose()
  }
}

$nameAliases = @{}
$aliasPath = Join-Path $PSScriptRoot 'photo-name-aliases.json'
if (Test-Path -LiteralPath $aliasPath) {
  $aliasObj = Get-Content -LiteralPath $aliasPath -Raw -Encoding UTF8 | ConvertFrom-Json
  $nameAliases = @{}
  $aliasObj.PSObject.Properties | ForEach-Object { $nameAliases[$_.Name] = $_.Value }
}

function Get-NameFromFileName {
  param([string]$FileName)
  $stem = [System.IO.Path]::GetFileNameWithoutExtension($FileName)
  $stem = $stem -replace '\(\d+\)$', ''
  $stem = $stem -replace '-\u62A0\u56FE$', ''
  if ($nameAliases.ContainsKey($stem)) { return $nameAliases[$stem] }
  return $stem
}

$map = @{}
Get-ChildItem -LiteralPath $PhotoDir -File | Where-Object {
  $_.Extension -match '\.(png|jpe?g|webp)$'
} | ForEach-Object {
  $personName = Get-NameFromFileName $_.Name
  $uri = Get-CompressedDataUri -Path $_.FullName -MaxSize $MaxSize -Quality $JpegQuality
  $map[$personName] = $uri
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/** @file photos-data.js - generated by import-photos.ps1 */')
[void]$sb.AppendLine('const PHOTO_DATA = {')
$keys = @($map.Keys | Sort-Object)
for ($i = 0; $i -lt $keys.Count; $i++) {
  $k = $keys[$i]
  $jsonKey = ($k | ConvertTo-Json -Compress)
  $jsonVal = ($map[$k] | ConvertTo-Json -Compress)
  $comma = if ($i -lt $keys.Count - 1) { ',' } else { '' }
  [void]$sb.AppendLine(('  ' + $jsonKey + ': ' + $jsonVal + $comma))
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('function applyPhotoDataToConfig() {')
[void]$sb.AppendLine('  if (typeof INCENTIVE_CONFIG === ''undefined'' || !PHOTO_DATA) return;')
[void]$sb.AppendLine('  var PHOTO_EMPLOYEE_ALIASES = {')
[void]$sb.AppendLine('    ''冯靖、裴俊智、高志圣、侯庆康'': ''数据安全团队''')
[void]$sb.AppendLine('  };')
[void]$sb.AppendLine('  function applyPhoto(emp) {')
[void]$sb.AppendLine('    if (!emp) return;')
[void]$sb.AppendLine('    if (emp.members && emp.members.length) {')
[void]$sb.AppendLine('      emp.members.forEach(function (m) {')
[void]$sb.AppendLine('        if (m.name && PHOTO_DATA[m.name]) m.photo = PHOTO_DATA[m.name];')
[void]$sb.AppendLine('      });')
[void]$sb.AppendLine('      return;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('    var photoKey = PHOTO_EMPLOYEE_ALIASES[emp.name] || emp.name;')
[void]$sb.AppendLine('    if (photoKey && PHOTO_DATA[photoKey]) emp.photo = PHOTO_DATA[photoKey];')
[void]$sb.AppendLine('  }')
[void]$sb.AppendLine('  [INCENTIVE_CONFIG.management, INCENTIVE_CONFIG.sales].forEach(function (dept) {')
[void]$sb.AppendLine('    (dept.months || []).forEach(function (month) {')
[void]$sb.AppendLine('      (month.employees || []).forEach(applyPhoto);')
[void]$sb.AppendLine('    });')
[void]$sb.AppendLine('  });')
[void]$sb.AppendLine('}')
[void]$sb.AppendLine('applyPhotoDataToConfig();')

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output ('OK ' + $outFile + ' ' + $map.Count)
